networks:
  traefik:
    external: true

services:
  send:
    image: registry.gitlab.com/timvisee/send:latest
    container_name: send
    networks:
      - traefik
    volumes:
      - send-data:/data
    restart: unless-stopped
    environment:
      - BASE_URL=https://send.whitney.rip
    labels:
      - traefik.http.routers.send.rule=Host(`send.whitney.rip`)
      - traefik.http.routers.send.tls=true
      - traefik.http.routers.send.tls.certresolver=lets-encrypt
      - traefik.http.services.send.loadbalancer.server.port=1443

volumes:
  send-data:

