networks:
  traefik:
    external: true

services:
  metube: 
    image: ghcr.io/alexta69/metube
    container_name: metube
    restart: unless-stopped
    networks:
      - traefik
    volumes:
      - /data/write/metube/downloads:/downloads
    environment:
      - DEFAULT_THEME=dark
    labels:
      - "traefik.http.routers.metube.rule=Host(`yt.whitney.rip`)"
      - "traefik.http.routers.metube.tls=true"
      - "traefik.http.routers.metube.tls.certresolver=lets-encrypt"
      - "traefik.http.services.metube.loadbalancer.server.port=8081"

