networks:
  traefik:
    external: true

services:
  admin:
    image: photoprism/photoprism
    container_name: photoprism-admin
    restart: unless-stopped
    networks:
      - traefik
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    env_file:
      - config-admin.env
    volumes:
      - /pwspool/software/photoprism/storage:/photoprism/storage
      - /pwspool/software/photoprism/originals:/photoprism/originals
    labels:
      - traefik.http.routers.private-photos.rule=Host(`photos.whitney.rip`)
      - traefik.http.routers.private-photos.tls=true
      - traefik.http.routers.private-photos.tls.certresolver=lets-encrypt
      - traefik.http.services.private-photos.loadbalancer.server.port=2342

  public:
    image: photoprism/photoprism
    container_name: photoprism-public
    restart: unless-stopped
    networks:
      - traefik
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    env_file:
      - config-public.env
    volumes:
      - /pwspool/software/photoprism/storage:/photoprism/storage
      - /pwspool/software/photoprism/originals:/photoprism/originals
    labels:
      - traefik.http.routers.public-photos.rule=Host(`gallery.whitney.rip`)
      - traefik.http.routers.public-photos.tls=true
      - traefik.http.routers.public-photos.tls.certresolver=lets-encrypt
      - traefik.http.services.public-photos.loadbalancer.server.port=2342

