networks:
  traefik:
    external: true

services:
  plex: 
    image: ghcr.io/linuxserver/plex:latest
    container_name: plex
    restart: unless-stopped
    networks:
      - traefik
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
    volumes:
      - /pwspool/archive/plex/:/config
      - /pwspool/archive/plex/tvseries:/tv
      - /pwspool/archive/plex/movies:/movies
      - /pwspool/archive/plex/photos:/photos
      - /pwspool/archive/plex/homevideos:/homevideos
      - /pwspool/archive/plex/transcode:/transcode
    ports:
      - "32400:32400"
    labels:
      - traefik.enable=false 

