version: "3"

networks:
  traefik_traefik-network:
    external: true
volumes:
  portainer_data:

services:
  portainer:
    image: portainer/portainer-ce 
    container_name: portainer
    restart: always
    networks:
      - traefik_traefik-network
    ports:
      - "8000:8000"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - portainer_data:/data
    labels:
      - traefik.http.routers.portainer.rule=Host(`admin.whitney.rip`)
      - traefik.http.routers.portainer.tls=true
      - traefik.http.routers.portainer.tls.certresolver=lets-encrypt
      - traefik.http.services.whoami.loadbalancer.server.port=9000
