version: "3.4"

networks:
  traefik_traefik-network:
    external: true


services:
  app:
    image: monica
    depends_on:
      - db
    ports:
      - 8022:80
    networks:
      - traefik_traefik-network
    environment:
      - APP_KEY=base64:Hl8b+vnvibkFbOR0CPQVmt5mLCB0mnXqfo8aIbNPRxo=
      - DB_HOST=db
      - DB_USERNAME=monica
      - DB_PASSWORD=secret
    volumes:
      - data:/var/www/html/storage
    restart: always
    labels:
      - traefik.http.routers.monica.rule=Host(`monica.whitney.rip`)
      - traefik.http.routers.monica.tls=true
      - traefik.http.routers.monica.tls.certresolver=lets-encrypt
      - traefik.http.services.monica.loadbalancer.server.port=8022
      - traefik.port=8022

  db:
    image: mysql:5.7
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=monica
      - MYSQL_USER=monica
      - MYSQL_PASSWORD=secret
    volumes:
      - mysql:/var/lib/mysql
    restart: always

volumes:
  data:
    name: data
  mysql:
    name: mysql

